# Generated by Django 5.2.10 on 2026-01-08 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCredentials',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company_credentials',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company.companycredentials')),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyJobDescription',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_role', models.CharField(max_length=150)),
                ('required_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('jd_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companycredentials')),
            ],
            options={
                'db_table': 'company_job_description',
            },
        ),
        migrations.CreateModel(
            name='JobRequiredSkills',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyjobdescription')),
            ],
            options={
                'db_table': 'job_required_skills',
                'unique_together': {('job', 'skill_name')},
            },
        ),
    ]
