# Generated by Django 5.2.10 on 2026-01-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('applicant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255)),
                ('resume_title', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('ats_score', models.IntegerField()),
                ('applied_date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyjobdescription')),
            ],
            options={
                'db_table': 'job_applicant',
            },
        ),
    ]
