# Generated by Django 5.2.10 on 2026-01-11 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyprofile_address_companyprofile_benefits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyjobdescription',
            old_name='jd_text',
            new_name='requirements',
        ),
        migrations.RemoveField(
            model_name='companyjobdescription',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='companyjobdescription',
            name='required_experience',
        ),
        migrations.AddField(
            model_name='companyjobdescription',
            name='benefits',
            field=models.TextField(blank=True, default='Intern', null=True),
        ),
        migrations.AddField(
            model_name='companyjobdescription',
            name='employment_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyjobdescription',
            name='experience_level',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyjobdescription',
            name='job_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyjobdescription',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyjobdescription',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyjobdescription',
            name='salary',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyjobdescription',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobdescription',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
